import initialState from './initialState'

import { createActionTypes } from 'lib'
import { Types } from 'store/api-utils'

export const UPLOAD_OBJECT = 'UPLOAD_OBJECT'
export const SET_UPLOAD_PROGRESS = 'SET_UPLOAD_PROGRESS'
export const SET_ALL_FILES = 'SET_ALL_FILES'
export const LIST_OBJECTS = 'LIST_OBJECTS'
export const GET_PATH_FILES = 'GET_PATH_FILES'
export const DOWNLOAD_OBJECT = 'DOWNLOAD_OBJECT'
export const PLAY_VIDEO = 'PLAY_VIDEO'
export const PAUSE_VIDEO = 'PAUSE_VIDEO'
export const ADD_VIDEO_LOADING = 'ADD_VIDEO_LOADING'
export const REMOVE_VIDEO_LOADING = 'REMOVE_VIDEO_LOADING'
export const CLEAR_ALL_VIDEO_LOADINGS = 'CLEAR_ALL_VIDEO_LOADINGS'
export const ADD_TEMP_IMAGE_URL = 'ADD_TEMP_IMAGE_URL'
export const REMOVE_TEMP_IMAGE_URL = 'REMOVE_TEMP_IMAGE_URL'
export const CLEAR_ALL_TEMP_IMAGE_URLS = 'CLEAR_ALL_TEMP_IMAGE_URLS'
export const SET_MULTI_SELECTION = 'SET_MULTI_SELECTION'
export const ADD_TO_MULTI_SELECTION = 'ADD_TO_MULTI_SELECTION'
export const REMOVE_FROM_MULTI_SELECTION = 'REMOVE_FROM_MULTI_SELECTION'
export const CLEAR_MULTI_SELECTION_LIST = 'CLEAR_MULTI_SELECTION_LIST'
export const ADD_FILE_OPERATION = 'ADD_FILE_OPERATION'
export const REMOVE_FILE_OPERATION = 'REMOVE_FILE_OPERATION'
export const CLEAR_FILE_OPERATIONS = 'CLEAR_FILE_OPERATIONS'
export const ADD_DOWNLOAD_LOADING = 'ADD_DOWNLOAD_LOADING'
export const REMOVE_DOWNLOAD_LOADING = 'REMOVE_DOWNLOAD_LOADING'
export const CLEAR_ALL_DOWNLOAD_LOADINGS = 'CLEAR_ALL_DOWNLOAD_LOADINGS'
export const MULTI_DOWNLOAD = 'MULTI_DOWNLOAD'
export const MULTI_OPERATION = 'MULTI_OPERATION'

export const types: Types = createActionTypes([
  UPLOAD_OBJECT,
  SET_UPLOAD_PROGRESS,
  SET_ALL_FILES,
  LIST_OBJECTS,
  GET_PATH_FILES,
  DOWNLOAD_OBJECT,
  PLAY_VIDEO,
  PAUSE_VIDEO,
  ADD_VIDEO_LOADING,
  CLEAR_ALL_VIDEO_LOADINGS,
  ADD_TEMP_IMAGE_URL,
  REMOVE_TEMP_IMAGE_URL,
  CLEAR_ALL_TEMP_IMAGE_URLS,
  SET_MULTI_SELECTION,
  ADD_TO_MULTI_SELECTION,
  REMOVE_FROM_MULTI_SELECTION,
  CLEAR_MULTI_SELECTION_LIST,
  ADD_FILE_OPERATION,
  REMOVE_FILE_OPERATION,
  CLEAR_FILE_OPERATIONS,
  ADD_DOWNLOAD_LOADING,
  REMOVE_DOWNLOAD_LOADING,
  CLEAR_ALL_DOWNLOAD_LOADINGS,
  MULTI_DOWNLOAD,
  MULTI_OPERATION,
])

export type ObjectState = typeof initialState

export default types
