version: '3.2'

services:

  webapp:
    container_name: zus-webapp
    build:
      context: ../
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3007:3000
    networks:
      - proxy-tier

networks:
  proxy-tier:
    driver: bridge